SNS_TOPIC_ARN = 'ARN of the SNS Topic'
S3_BUCKET_NAME = 'Name of the AWS bucket to be used'
DNAMODB_TABLE = 'Name of the DynamoDB table'
RDS_SECRET_NAME = 'Secret manager data from RDS'
ECS_API_URL = 'URL of the ECS cluster (LB URL)'
LAMBDA_API_URL = 'URL of the API GW attached with AWS Lambda'
